import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import "../assets/styles/PatientSharedHistory.css";

const API_BASE_URL =
  import.meta.env.VITE_API_URL || "http://localhost:8081";

const PatientSharedHistory = () => {
  const navigate = useNavigate();
  const token = localStorage.getItem("patientToken");

  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!token) {
      navigate("/patient-login");
      return;
    }

    fetchSharedHistory();
  }, [token, navigate]);

  const getAuthConfig = () => {
    return {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    };
  };

  const fetchSharedHistory = async () => {
    try {
      setLoading(true);

      const response = await axios.get(
        `${API_BASE_URL}/api/patient/share/history`,
        getAuthConfig()
      );

      const sortedHistory = response.data.sort(
        (a, b) => new Date(b.createdAt) - new Date(a.createdAt)
      );

      setHistory(sortedHistory);
    } catch (error) {
      console.log("FETCH SHARED HISTORY ERROR:", error);
      console.log("BACKEND RESPONSE:", error.response?.data);

      alert(
        error.response?.data?.message ||
          error.response?.data ||
          "Failed to fetch shared history"
      );
    } finally {
      setLoading(false);
    }
  };

  const revokeAccess = async (accessId) => {
    const confirmRevoke = window.confirm(
      "Are you sure you want to revoke this QR access?"
    );

    if (!confirmRevoke) {
      return;
    }

    try {
      const response = await axios.put(
        `${API_BASE_URL}/api/patient/share/revoke/${accessId}`,
        {},
        getAuthConfig()
      );

      alert(response.data.message);
      fetchSharedHistory();
    } catch (error) {
      console.log("REVOKE ERROR:", error);
      console.log("BACKEND RESPONSE:", error.response?.data);

      alert(
        error.response?.data?.message ||
          error.response?.data ||
          "Failed to revoke access"
      );
    }
  };

  const copyLink = async (accessLink) => {
    if (!accessLink) {
      alert("Access link not available");
      return;
    }

    try {
      await navigator.clipboard.writeText(accessLink);
      alert("Access link copied");
    } catch (error) {
      alert("Failed to copy link");
    }
  };

  const formatDate = (dateValue) => {
    if (!dateValue) {
      return "Not Available";
    }

    return new Date(dateValue).toLocaleString();
  };

  const isExpired = (item) => {
    if (item.expired === true) {
      return true;
    }

    if (!item.expiresAt) {
      return false;
    }

    return new Date(item.expiresAt) <= new Date();
  };

  const isUsable = (item) => {
    return item.active === true && !isExpired(item);
  };

  const getStatusText = (item) => {
    if (!item.active) {
      return "REVOKED";
    }

    if (isExpired(item)) {
      return "EXPIRED";
    }

    return "ACTIVE";
  };

  const getStatusClass = (item) => {
    if (!item.active) {
      return "history-status-revoked";
    }

    if (isExpired(item)) {
      return "history-status-expired";
    }

    return "history-status-active";
  };

  return (
    <div className="shared-history-page">
      <aside className="shared-history-sidebar">
        <div className="shared-history-logo">🔐</div>

        <h2>MediLink AI</h2>
        <p>Patient Portal</p>

        <button onClick={() => navigate("/patient-dashboard")}>
          ← Back to Dashboard
        </button>
      </aside>

      <main className="shared-history-main">
        <header className="shared-history-header">
          <div>
            <h1>Shared History</h1>
            <p>View and manage all QR access links generated by you.</p>
          </div>

          <button onClick={() => navigate("/patient/qr-sharing")}>
            + Generate New QR
          </button>
        </header>

        {loading ? (
          <div className="history-empty-box">
            <p>Loading shared history...</p>
          </div>
        ) : history.length === 0 ? (
          <div className="history-empty-box">
            <div>🔐</div>
            <p>No shared QR history yet.</p>
            <span>Generate QR access first to see history here.</span>

            <button onClick={() => navigate("/patient/qr-sharing")}>
              Generate QR
            </button>
          </div>
        ) : (
          <section className="history-grid">
            {history.map((item) => (
              <div className="history-card" key={item.accessId}>
                <div className="history-card-top">
                  <div className="history-icon">📱</div>

                  <div>
                    <h3>QR Access #{item.accessId}</h3>
                    <p>{formatDate(item.createdAt)}</p>
                  </div>

                  <span className={getStatusClass(item)}>
                    {getStatusText(item)}
                  </span>
                </div>

                <div className="history-details">
                  <p>
                    <strong>Selected Reports:</strong>{" "}
                    {item.selectedReportsCount || "Not Available"}
                  </p>

                  <p>
                    <strong>Created At:</strong> {formatDate(item.createdAt)}
                  </p>

                  <p>
                    <strong>Expires At:</strong> {formatDate(item.expiresAt)}
                  </p>

                  <p>
                    <strong>Access Token:</strong>{" "}
                    <span className="history-token">{item.accessToken}</span>
                  </p>
                </div>

                <div className="history-link-box">
                  <label>Access Link</label>
                  <input value={item.accessLink || ""} readOnly />
                </div>

                <div className="history-actions">
                  <button onClick={() => copyLink(item.accessLink)}>
                    Copy Link
                  </button>

                  <button
                    onClick={() => window.open(item.accessLink, "_blank")}
                    disabled={!isUsable(item)}
                  >
                    Open Link
                  </button>

                  <button
                    className="history-revoke-btn"
                    onClick={() => revokeAccess(item.accessId)}
                    disabled={!item.active}
                  >
                    Revoke
                  </button>
                </div>

                {!isUsable(item) && (
                  <div className="history-note">
                    This QR access is not usable now.
                  </div>
                )}
              </div>
            ))}
          </section>
        )}
      </main>
    </div>
  );
};

export default PatientSharedHistory;